kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cloud-resource-operator-rds-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cloud-resource-operator-rds-role
subjects:
- kind: ServiceAccount
  name: cloud-resource-operator
  namespace: redhat-ods-operator
