kind: Deployment
apiVersion: apps/v1
metadata:
  name: cloud-resource-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: cloud-resource-operator
  template:
    metadata:
      labels:
        name: cloud-resource-operator
    spec:
      containers:
        - name: cloud-resource-operator
          image: 'quay.io/modh/cloud-resource-operator-container:v0.39.0'
          command:
            - cloud-resource-operator
          env:
            - name: WATCH_NAMESPACE
              value: redhat-ods-applications
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: cloud-resource-operator
            - name: TAG_KEY_PREFIX
              value: integreatly.org/
            - name: OPERATOR_CONDITION_NAME
              value: cloud-resources.v0.39.0
          resources:
            limits:
              cpu: 50m
              memory: 75Mi
            requests:
              cpu: 25m
              memory: 50Mi
          readinessProbe:
            tcpSocket:
              port: 8383
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            tcpSocket:
              port: 8383
            initialDelaySeconds: 30
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      serviceAccountName: cloud-resource-operator
      serviceAccount: cloud-resource-operator
      securityContext: {}
      schedulerName: default-scheduler
