---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: redhat-monitoring
spec:
  selector:
    matchLabels:
      app: grafana
  replicas: 2
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: quay.io/app-sre/grafana:7.4.0
          ports:
          - containerPort: 3000
            name: http
            protocol: TCP
          readinessProbe:
            httpGet:
              path: /api/health
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 5
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /api/health
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: grafana
spec:
  ports:
    - name: http
      port: 443
      protocol: TCP
      targetPort: 3000
  selector:
    app: grafana

---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: grafana
spec:
  port:
    targetPort: http
  to:
    kind: Service
    name: grafana
    weight: 100
  wildcardPolicy: None
