apiVersion: kfdef.apps.kubeflow.org/v1
kind: KfDef
metadata:
  name: opendatahub
spec:
  applications:
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: odh-common
    name: odh-common
  - kustomizeConfig:
      parameters:
        - name: jupyterhub_groups_config
          value: rhods-groups-config
        - name: notebook_destination
          value: rhods-notebooks
      repoRef:
        name: manifests
        path: jupyterhub/jupyterhub
    name: jupyterhub
  - kustomizeConfig:
      overlays:
        - jupyterhub-rds-db-patches
        - ui-config
        - ../overlays/jupyterhub-idle-culler
      repoRef:
        name: manifests
        path: jupyterhub/jupyterhub/overrides
    name: jupyterhub
  - kustomizeConfig:
      overlays:
      - additional
      repoRef:
        name: manifests
        path: jupyterhub/notebook-images
    name: notebook-images
  - kustomizeConfig:
      overlays:
        - authentication
      repoRef:
        name: manifests
        path: odh-dashboard
    name: odh-dashboard
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: partners/anaconda
    name: anaconda-ce
  repos:
  - name: manifests
    uri: file:///opt/manifests/odh-manifests.tar.gz
  version: v1.0.0
