---
apiVersion: v1
stringData:
  grafana.ini: |-
    [auth]
    disable_login_form = true
    disable_signout_menu = true
    [auth.anonymous]
    enabled = true
    # Role for unauthenticated users, other valid values are `Editor` and `Admin`
    org_role = Viewer
    [auth.basic]
    enabled = false
    [auth.proxy]
    auto_sign_up = true
    enabled = true
    header_name = X-Forwarded-User
    [paths]
    data = /var/lib/grafana
    logs = /var/lib/grafana/logs
    plugins = /var/lib/grafana/plugins
    provisioning = /etc/grafana/provisioning
    [server]
    http_addr = 0.0.0.0
    http_port = 3001
    [users]
    viewers_can_edit = true
    [metrics]
    enabled = true
    [alerting]
    enabled = false
    [dataproxy]
    timeout = 900
kind: Secret
metadata:
  name: grafana-config
  namespace: redhat-ods-monitoring
type: Opaque

---
apiVersion: v1
stringData:
  session_secret: <change_proxy_secret>
kind: Secret
metadata:
  name: grafana-proxy-config
  namespace: redhat-ods-monitoring
type: Opaque

---
apiVersion: v1
stringData:
  datasources.yaml: |-
    {
      "apiVersion": 1,
      "datasources": [
          {
              "name": "Monitoring",
              "type": "prometheus",
              "typeLogoUrl": "",
              "access": "proxy",
              "url": "https://<change_route>",
              "basicAuth": false,
              "withCredentials": false,
              "jsonData": {
                  "tlsSkipVerify": true,
                  "httpHeaderName1": "Authorization"
              },
              "secureJsonData": {
                  "httpHeaderValue1": "Bearer <change_token>"
              }
          }
      ]
    }
kind: Secret
metadata:
  name: grafana-datasources
  namespace: redhat-ods-monitoring
type: Opaque
