apiVersion: kfdef.apps.kubeflow.org/v1
kind: KfDef
metadata:
  name: rhods-model-mesh
spec:
  applications:
    - kustomizeConfig:
        parameters:
        - name: odh-mm-rest-proxy
          value: ${RELATED_IMAGE_ODH_MM_REST_PROXY_IMAGE}
        - name: odh-modelmesh-runtime-adapter
          value: ${RELATED_IMAGE_ODH_MODELMESH_RUNTIME_ADAPTER_IMAGE}
        - name: odh-modelmesh
          value: ${RELATED_IMAGE_ODH_MODELMESH_IMAGE}
        - name: odh-modelmesh-controller
          value: ${RELATED_IMAGE_ODH_MODELMESH_CONTROLLER_IMAGE}
        - name: odh-model-controller
          value: ${RELATED_IMAGE_ODH_MODEL_CONTROLLER_IMAGE}
        - name: monitoring-namespace
          value: redhat-ods-monitoring
        overlays:
          - odh-model-controller
        repoRef:
          name: manifests
          path: model-mesh
      name: model-mesh
  repos:
    - name: manifests
      uri: file:///opt/manifests/odh-manifests.tar.gz
  version: v1.0.0
