apiVersion: kfdef.apps.kubeflow.org/v1
kind: KfDef
metadata:
  name: monitoring
spec:
  applications:
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: monitoring
    name: monitoring
  repos:
  - name: manifests
    uri: file:///opt/manifests/odh-manifests.tar.gz
  version: v1.0.0
