apiVersion: kfdef.apps.kubeflow.org/v1
kind: KfDef
metadata:
  name: rhods-data-science-pipelines-operator
spec:
  applications:
    - kustomizeConfig:
        parameters:
          - name: IMAGES_APISERVER
            value: ${RELATED_IMAGE_ODH_ML_PIPELINES_API_SERVER_IMAGE}
          - name: IMAGES_ARTIFACT
            value: ${RELATED_IMAGE_ODH_ML_PIPELINES_ARTIFACT_MANAGER_IMAGE}
          - name: IMAGES_PERSISTENTAGENT
            value: ${RELATED_IMAGE_ODH_ML_PIPELINES_PERSISTENCEAGENT_IMAGE}
          - name: IMAGES_SCHEDULEDWORKFLOW
            value: ${RELATED_IMAGE_ODH_ML_PIPELINES_SCHEDULEDWORKFLOW_IMAGE}
          - name: IMAGES_CACHE
            value: ${RELATED_IMAGE_ODH_ML_PIPELINES_CACHE_IMAGE}
          - name: IMAGES_DSPO
            value: ${RELATED_IMAGE_ODH_DATA_SCIENCE_PIPELINES_OPERATOR_CONTROLLER_IMAGE}
          - name: IMAGES_MOVERESULTSIMAGE
            value: registry.redhat.io/ubi8/ubi-micro@sha256:6a56010de933f172b195a1a575855d37b70a4968be8edb35157f6ca193969ad2
          - name: IMAGES_MARIADB
            value: registry.redhat.io/rhel8/mariadb-103@sha256:08c90a8f133b4cdb1477a742bc44be4d8fc4e88153b8bc2a2a148cbdf19f4e7d
        repoRef:
          name: manifests
          path: data-science-pipelines-operator/
      name: data-science-pipelines-operator
  repos:
    - name: manifests
      uri: file:///opt/manifests/odh-manifests.tar.gz
  version: v1.0.0
