apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app: prometheus
  name: prometheus
  namespace: redhat-odh-monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: prometheus
  template:
    metadata:
      labels:
        deployment: prometheus
    spec:
      serviceAccountName: prometheus
      containers:
      - name: oauth-proxy
        args:
        - -provider=openshift
        - -https-address=:9091
        - -http-address=
        - -email-domain=*
        - -upstream=http://localhost:9090
        - -openshift-service-account=prometheus
        - '-openshift-sar={"resource": "namespaces", "verb": "get", "name": "redhat-odh-monitoring",
          "namespace": "redhat-odh-monitoring"}'
        - '-openshift-delegate-urls={"/": {"resource": "namespaces", "verb": "get",
          "name": "redhat-odh-monitoring", "namespace": "redhat-odh-monitoring"}}'
        - -tls-cert=/etc/tls/private/tls.crt
        - -tls-key=/etc/tls/private/tls.key
        - -client-secret-file=/var/run/secrets/kubernetes.io/serviceaccount/token
        - -cookie-secret-file=/etc/proxy/secrets/session_secret
        - -openshift-ca=/etc/pki/tls/cert.pem
        - -openshift-ca=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        - -client-id=system:serviceaccount:redhat-odh-monitoring:prometheus
        - -skip-auth-regex=^/metrics
        image: quay.io/openshift/origin-oauth-proxy:4.7.0
        ports:
        - containerPort: 9091
          name: https
        resources:
          limits:
            cpu: 100m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 256Mi
        volumeMounts:
        - mountPath: /etc/tls/private
          name: prometheus-tls
          readOnly: false
        - mountPath: /etc/proxy/secrets
          name: prometheus-proxy
          readOnly: false

      - name: prometheus
        image: quay.io/prometheus/prometheus:v2.24.1
        args:
          - --storage.tsdb.retention=6h
          - --storage.tsdb.min-block-duration=2h
          - --storage.tsdb.max-block-duration=2h
          - --storage.tsdb.path=/prometheus/data
          - --config.file=/etc/prometheus/prometheus.yml
          - --web.listen-address=localhost:9090
          - --web.enable-lifecycle
          - --web.enable-admin-api
        imagePullPolicy: Always
        ports:
        - containerPort: 9090
          name: http
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /prometheus
          name: prometheus-data
        - mountPath: /etc/prometheus
          name: prometheus-config
        - mountPath: /var/run/secrets/kubernetes.io/scraper
          name: prometheus-secret

      - name: alertmanager-proxy
        args:
        - -provider=openshift
        - -https-address=:10443
        - -http-address=
        - -email-domain=*
        - -upstream=http://localhost:9093
        - -openshift-service-account=prometheus
        - '-openshift-sar={"resource": "namespaces", "verb": "get", "name": "redhat-odh-monitoring",
          "namespace": "redhat-odh-monitoring"}'
        - '-openshift-delegate-urls={"/": {"resource": "namespaces", "verb": "get",
          "name": "redhat-odh-monitoring", "namespace": "redhat-odh-monitoring"}}'
        - -tls-cert=/etc/tls/private/tls.crt
        - -tls-key=/etc/tls/private/tls.key
        - -client-secret-file=/var/run/secrets/kubernetes.io/serviceaccount/token
        - -cookie-secret-file=/etc/proxy/secrets/session_secret
        - -openshift-ca=/etc/pki/tls/cert.pem
        - -openshift-ca=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        - -client-id=system:serviceaccount:redhat-odh-monitoring:prometheus
        - -skip-auth-regex=^/metrics
        image: quay.io/openshift/origin-oauth-proxy:4.7.0
        imagePullPolicy: Always
        ports:
        - containerPort: 10443
          name: web
        resources:
          limits:
            cpu: 100m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 256Mi
        volumeMounts:
        - mountPath: /etc/tls/private
          name: alertmanager-tls
          readOnly: false
        - mountPath: /etc/proxy/secrets
          name: alertmanager-proxy
          readOnly: false

      - name: alertmanager
        args:
          - --log.level=info
          - --config.file=/etc/alertmanager/alertmanager.yml
          - --web.external-url=https://<set_alertmanager_host>
        image: quay.io/prometheus/alertmanager:v0.21.0
        imagePullPolicy: Always
        ports:
          - containerPort: 9093
            name: web
        volumeMounts:
          - mountPath: /etc/alertmanager
            name: alertmanager-config
          - mountPath: /alertmanager
            name: alertmanager-data

      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 90
      volumes:
      - name: prometheus-data
        persistentVolumeClaim:
          claimName: prometheus-data
      - name: alertmanager-data
        persistentVolumeClaim:
          claimName: "alertmanager-data"
      - name: alertmanager-config
        configMap:
          defaultMode: 420
          name: alertmanager
      - name: prometheus-config
        configMap:
          defaultMode: 420
          name: prometheus
      - name: prometheus-secret
        secret:
          secretName: prometheus-secret
      - name: prometheus-tls
        secret:
          defaultMode: 420
          secretName: prometheus-tls
      - name: alertmanager-tls
        secret:
          defaultMode: 420
          secretName: alertmanager-tls
      - name: prometheus-proxy
        secret:
          defaultMode: 420
          secretName: prometheus-proxy
      - name: alertmanager-proxy
        secret:
          defaultMode: 420
          secretName: alertmanager-proxy

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus
  namespace: redhat-odh-monitoring
data:
  recording.rules: |
    groups:
      - name: notebook_count
        rules:
        - record: notebook_count
          expr: jupyterhub_running_servers

  alerting.rules: |
    groups:
      - name: Pod Restarts
        interval: 1m
        rules:
          - alert: An OpenShift pod has just restarted
            expr: sum(delta(kube_pod_container_status_restarts_total{namespace="opendatahub", pod!~"jupyterhub-nb-.*"}[5m])) by (namespace, pod) > 0
            for: 5m
            annotations:
              summary: An OpenShift pod has just been restarted.
              action: Check {{ $labels.kubernetes_pod_name }} pod in {{ $labels.kubernetes_namespace}} namespace to determine why the pod is restarting.
              route: idh_router

  prometheus.yml: |
    rule_files:
      - '*.rules'
    global:
      scrape_interval:     10s
      evaluation_interval: 10s

    scrape_configs:
    - job_name: 'Federate Prometheus'
      scrape_interval: 30s
      scheme: https
      tls_config:
        insecure_skip_verify: true
        ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      bearer_token: "<prom_bearer_token>"
      honor_labels: true
      metrics_path: '/federate'

      params:
        'match[]':
          - '{job=~"[A-z].*"}'

      static_configs:
        - targets:
          - "<federate_target>"

    - job_name: 'JupyterHub Metrics'
      honor_labels: true
      metrics_path: /hub/metrics
      scheme: http
      kubernetes_sd_configs:
        - role: endpoints
          namespaces:
            names:
              - opendatahub
      relabel_configs:
        - source_labels: [__meta_kubernetes_service_name]
          regex: ^(jupyterhub)$
          target_label: kubernetes_name
          action: keep
        - source_labels: [__address__]
          regex: (.+):(\d+)
          target_label: __address__
          replacement: ${1}:8080

    alerting:
      alertmanagers:
      - scheme: http
        static_configs:
        - targets:
          - "localhost:9093"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager
  namespace: redhat-odh-monitoring
data:
  alertmanager.yml: |
    global:
      smtp_smarthost: 'smtp.corp.redhat.com:25'
      smtp_from: 'AlertManager-Production@redhat.com'
      smtp_auth_username: 'alertmanager'
      smtp_auth_password: 'password'
      smtp_require_tls: false
    # The root route on which each incoming alert enters.
    route:
      group_by: ['alertname', 'cluster', 'service', 'job', 'email_to']

      group_wait: 30s

      # When the first notification was sent, wait 'group_interval' to send a batch
      # of new alerts that started firing for that group.
      group_interval: 5m

      # If an alert has successfully been sent, wait 'repeat_interval' to
      # resend them.
      repeat_interval: 4h

      # A default receiver
      receiver: developer-mails

      # All the above attributes are inherited by all child routes and can
      # overwritten on each.
      routes:
      - match:
          route: idh_router
        receiver: idh_router

    receivers:
    - name: 'developer-mails'
      email_configs:
      - to: 'data-hub-alerts@redhat.com'
        send_resolved: true

    - name: 'idh_router'
      email_configs:
      - to: 'data-hub-alerts@redhat.com'
        send_resolved: true

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: alertmanager-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: prometheus-tls
    prometheus.io/scheme: https
    prometheus.io/scrape: 'true'
  labels:
    app: prometheus
  name: prometheus
  namespace: redhat-odh-monitoring
spec:
  ports:
  - name: https
    port: 9091
    targetPort: https
  selector:
    deployment: prometheus
  sessionAffinity: None
  type: ClusterIP

---
# Create a service account for accessing prometheus data
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus-reader
  namespace: redhat-odh-monitoring
---
apiVersion: v1
kind: Secret
metadata:
  name: prometheus-secret
  namespace: redhat-odh-monitoring
  annotations:
    kubernetes.io/service-account.name: prometheus
type: kubernetes.io/service-account-token
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    kubernetes.io/tls-acme: 'true'
  labels:
    app: prometheus
  name: prometheus
  namespace: redhat-odh-monitoring
spec:
  port:
    targetPort: https
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: reencrypt
  to:
    kind: Service
    name: prometheus
  wildcardPolicy: None
---
apiVersion: authorization.openshift.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus-scraper
roleRef:
  name: prometheus-scraper
subjects:
- kind: ServiceAccount
  name: prometheus
  namespace: redhat-odh-monitoring
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus-scraper
rules:
- apiGroups:
  - route.openshift.io
  resources:
  - routers/metrics
  - routers/federate
  verbs:
  - get
- apiGroups:
  - image.openshift.io
  resources:
  - registry/metrics
  verbs:
  - get
