---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
      serviceaccounts.openshift.io/oauth-redirectreference.prometheus: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"prometheus"}}'
      serviceaccounts.openshift.io/oauth-redirectreference.alertmanager: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"alertmanager"}}'
  name: prometheus
  namespace: redhat-ods-monitoring

---
apiVersion: v1
kind: Secret
metadata:
  name: prometheus-proxy
  namespace: redhat-ods-monitoring
data:
  session_secret: "<prometheus_proxy_secret>"
type: Opaque

---
apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-proxy
  namespace: redhat-ods-monitoring
data:
  session_secret: "<alertmanager_proxy_secret>"
type: Opaque

---
apiVersion: v1
kind: Secret
metadata:
  name: prometheus-secret
  namespace: redhat-ods-monitoring
  annotations:
    kubernetes.io/service-account.name: prometheus
type: kubernetes.io/service-account-token
