{
 "title": "Jupyterhub SLIs",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Availability SLIs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Jupyterhub Availability",
     "type": "graph",
     "description": "What is the current availability status of the Jupyterhub Master pod",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "up{job=\"Jupyterhub Metrics\"}",
       "legendFormat": "Jupyterhub"
      }
     ]
    },
    {
     "title": "TODO: Availability/Traffic for Jupyterhub Database",
     "type": "graph",
     "description": "We need to track if the jupyterhub db pod is up and running",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ]
    }
   ]
  },
  {
   "title": "Error SLIs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Notebook container creation errors",
     "type": "graph",
     "description": "This keeps a track of the errors encountered when spawning a notebook container.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "count(kube_pod_container_status_waiting_reason{pod=~\"jupyterhub-nb-.*\", reason=~\"CrashLoopBackOff|ErrImagePull|ImagePullBackOff\"} == 1) by(reason,pod)"
      }
     ]
    },
    {
     "title": "Jupyterhub Notebook Spawn Success Rate",
     "type": "graph",
     "description": "This keeps a track of what fraction of notebook server has succeeded in spawning",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(jupyterhub_server_spawn_duration_seconds_count{status=\"success\"})/sum(jupyterhub_server_spawn_duration_seconds_count{})",
       "legendFormat": "Jupyterhuv Server Spawn Success Rate"
      }
     ]
    },
    {
     "title": "Jupyterhub Main Pod Restarts",
     "type": "graph",
     "description": "This keeps track of the number of hub restarts",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg by (pod) (kube_pod_container_status_restarts_total{pod=~\"jupyterhub-\\\\d.*-\\\\D\\\\D\\\\D\\\\D\\\\D\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "OOMKilled Jupyterhub Pods",
     "type": "graph",
     "description": "Counts the number of pods that have been OOMKilled. This includes Jupyterhub, the DB, and User pods",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg by (pod) (sum_over_time(kube_pod_container_status_terminated_reason{pod=~\"jupyterhub-\\\\d.*-\\\\D\\\\D\\\\D\\\\D\\\\D|jupyterhub-db-\\\\d.*\", reason=\"OOMKilled\"}[1h]))",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Percentage of Jupyterhub requests that 5xx",
     "type": "graph",
     "description": "This counts the number of 5xx errors in JH operations.",
     "gridPos": { "h": 8, "w": 12, "x": 6, "y": 18 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(jupyterhub_request_duration_seconds_count{code=~\"5.*\"})/sum(jupyterhub_request_duration_seconds_count)"
      }
     ]
    }
   ]
  },
  {
   "title": "Latency SLIs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Jupyterhub Notebook Spawner Init time",
     "type": "bargauge",
     "description": "This measures the time it takes Jupyterhub to spin up a new notebook pod spawner",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "jupyterhub_init_spawners_duration_seconds_bucket",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Jupyterhub Startup Time",
     "type": "bargauge",
     "description": "This measures the time it takes for the main Jupyterhub pod to come online",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "jupyterhub_hub_startup_duration_seconds_bucket",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "TODO: Latency for Jupyterhub Database",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 6, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ]
    }
   ]
  },
  {
   "title": "Saturation SLIs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Jupyterhub Memory Usage",
     "type": "graph",
     "description": "This measures the memory usage of key Jupyterhub pods over time",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(container_memory_rss{pod=~\"jupyterhub-\\\\d.*|jupyterhub-db.*\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Jupyterhub CPU usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "(sum(rate(container_cpu_usage_seconds_total{pod=~\"jupyterhub-\\\\d.*|jupyterhub-db.*\"}[5m])) by (pod))*100",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Jupyterhub DB PVC Usage",
     "type": "graph",
     "description": "This expression monitors the current consumption % of the DB PVC. If it hits 100% the DB pod will not start up and we are at risk of data loss",
     "gridPos": { "h": 8, "w": 12, "x": 6, "y": 20 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "(avg by (persistentvolumeclaim) (kubelet_volume_stats_used_bytes{persistentvolumeclaim=~\"jupyterhub-db\"}))/(avg by (persistentvolumeclaim) (kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=~\"jupyterhub-db\"}))",
       "legendFormat": "{{persistentvolumeclaim}}"
      }
     ]
    }
   ]
  }
 ]
}